# Setup
title:               Nameless
tagline:             'There are only two hard things in Computer Science'
description:         'This is the description'
url:                 http://blog.mandre.org
baseurl:             ''
paginate:            5
github_username:  mandre

# About/contact
author:
  name:              Martin Andr√©
  url:               https://github.com/mandre

# Custom vars
version:             1.0.0

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript
